export const diploma_colleges = [
 "+3 Royal Commerce & Sc. (Degree) College, Royal Nagar",
"AARADHYA BUSINESS SCHOOL OF COMPUTER AND MANAGEMENT, BERHAMPUR",
"Aaryan Gurukul Degree College, Berhampur",
"Acharya Padman Nayak Memorial Degree College, Gumma",
"Adikabi Sarala Das (Degree) College, Tirtol",
"Alfa Best Degree College of Science & Tech., Tulasi Vihar",
"Anchalika (Degree) Mahavidyalaya, Dampara",
"Anchalika (Degree) Mahavidyalaya, Gadia",
"Anchalika (Degree) Mahavidyalaya, Jagannathprasad",
"Anchalika Degree Mahavidyalaya, Guneibil",
"Anchalika Science (Degree) College, Ballipadar",
"Angarpada Panchayat (Degree) College, Raruan",
"Ansupa Degree College, Saranda",
"Arjuna Degree College, Kadaligarh",
"Astaranga (Degree) College, Astaranga",
"Atal Bihari (Degree) College, Basudevpur",
"Aul (Degree) College, Aul",
"B.J.B. (Degree) College, Gadarodanga",
"Baba Bhairabananda (Autonomous) Mahavidyalaya, Chandikhol",
"Baba Hare Krushna Das (Degree) Mahavidyalaya, Markandpur",
"Babamani (Degree) Mahavidyalaya, Pallasahi",
"BAIKUNTHA NATH INSTITUTE OF HIGHER STUDIES, KACHUADI",
"Ballavi Devi Mahila (Degree) Mahavidyalaya, Natakai",
"BALUNKESWAR DEGREE COLLEGE, BALLIPADAR",
"Banamalipur (Degree) College, Banamalipur",
"Banki (Autonomous) College, Banki",
"Bapuji (Degree) College, Chhendipada",
"Barbil Degree (Degree) College, Barbil",
"Barpara (Degree) College, Barpara",
"Begunia (Degree) College, Begunia",
"Bellaguntha Science (Degree) College, Bellaguntha",
"Belpahar (Degree) College, Belpahar",
"Bhagya Degree College, Gyana Vihar",
"Bhakta Manein Smruti Degree Mhv., Kandagoda",
"Bharati Vihar (Degree) Mahavidyalaya, Haripur",
"Bidwan Residential Degree College, College Road",
"Bidyaniketan Degree College, Nabarangpur",
"Bighnesh Residential Degree College",
"Biju Patnaik (Degree) College, Antei",
"Biju Pattnaik (Degree) College, Ashrampatna",
"Biju Pattnaik (Degree) College, Boden",
"Binayak Degree College, Bhawanipatna",
"Biren Mitra Memorial Women's (Degree) College, Cuttack",
"Bishwaprava Degree College, Bahirkhaman",
"Brahmanajharilo (Degree) Mahavidyalaya, Brahmanajharilo",
"Braja Bandhu (Degree) Mahavidyalaya, Harichandanpur",
"Brundabana Subudhi (Degree) College, Daspalla",
"Burla N.A.C. (Degree) College, Burla",
"Buxi Jagabandhu Bidyadhar (Autonomous) College, Bhubaneswar",
"Chaitanya Sahu (Degree) College of Science & Arts, Nuapatna",
"Chhatrapur Women's (Degree) College, Chhatrapur",
"Chitalo (Degree) Mahavidyalaya, Chitalo",
"Christ (Degree) College, Cuttack",
"CNCB Academy of Science Technology, Basantapur",
"College of Arts, Science & Technology (Degree), Bondamunda",
"CUTM-Bhubaneswar Campus",
"CUTM-Bolangir Campus",
"Cuttack (Degree) College, Nayabazar",
"Dalmia (Degree) College, Jharbeda",
"Dandapani Maharatha Science (Degree) College, Gallery",
"DAV School of Business Management, Bhubaneswar",
"Debendra Satapathy Memorial (Degree) College, Bhapur",
"Delta Institute of Agriculture and Management, Baniatangi",
"Dharanidhar University, Keonjhar",
"Dhenkanal (Autonomous) College, Dhenkanal",
"Dhenkanal Evening (Degree) College, Dhenkanal",
"Dr. B.R. Ambedkar National (Degree) College, Ramagiri",
"Dr. Jadunath (Degree) College, Rasalpur",
"Dr. Rama Chandra Samantray (Degree) College, Gania",
"Dr. Shyama Prasad (Degree) College, M.V- 79",
"Dutika Sahu (Degree) College, Laida",
"Ekalabya Panchayat Samiti (Degree) College, Kansar",
"e-Tech Residential Degree College, Dakhinakali Road",
"Fakir Mohan (Autonomous) College, Balasore",
"Gadibrahma (Degree) College, Delang",
"Gandhi (Degree) Mahavidyalaya, Deogaon",
"Gangadhar Meher University, Sambalpur",
"Gangadhar Sahu Science Degree College, Hatiota",
"Gangeswari (Degree) Mahavidyalaya, Pottangi",
"Gatiswar (Degree) College, Malisahi",
"Gayatri +3 Science College, Dhangarpada",
"Gayatri +3 Science College, Mandiakudar, Rourkela",
"Gayatri +3 Science College, Nuagaon",
"Gayatri Institute of Computer and Management, Hinjilcut",
"Ghanteswar (Degree) College, Ghanteswar",
"Gokul Parvati Rural (Degree) College, Kuntara",
"Gopalpur (Degree) College, Gopalpur, Ganjam",
"Government (Autonomous) College, Angul",
"Government (Autonomous) College, Rourkela",
"Government (Degree) College, Bolangir",
"Government (Degree) College, Koraput",
"Government (Degree) College, Sundergarh",
"Government Science (Degree) College, Chhatrapur",
"Government Women's (Degree) College, Bhawanipatna",
"Government Women's (Degree) College, Keonjhar",
"Government Women's (Degree) College, Puri",
"Government Women's Degree College, Titilagarh",
"Govindpur (Degree) College, Govindpur",
"Gurukrupa Degree College, Raighar",
"Hariswar Dev Vocational Science (Degree) College, Panaspada",
"Hill Top (Degree) College, Mohana",
"Hirakud (Degree) College, Hirakud",
"Hrushikesh Ray (Degree) Mahavidyalaya, Chhend",
"Imperial Degree College, Vidya Vihar, Chadeigaon",
"Institute of Professional Studies and Research, Cuttack",
"Ispat (Autonomous) College, Rourkela",
"Jamankira (Degree) College, Jamankira",
"Janata (Degree) College, Kuhudi",
"Jatiya Kabi Bira Kishore Government (Degree) College, Cuttack",
"Jjoy Kisan Phillip Memorial Degree College, Kosagumuda",
"Joda Women's (Degree) College, Joda",
"JSM Commerce Degree College, Bolangir",
"Kabi Prasanna Patasani Anchalika (Degree) Mohavidyalaya, Malipada",
"Kalijai Degree College, Balugaon",
"Kalinga (Degree) College, Manada",
"Kalinga Bharati Residential (Degree) College, Pira Bazar",
"Kalinga College of Commerce, Samantarapur,Bhubaneswar",
"Kalyani Ray (Degree) Mahavidyalaya, Hamirpur",
"Kamala Nehru Women's (Degree) College, Bhubaneswar",
"Kanas (Degree) College, Kanas",
"Karanjia (Autonomous) College, Karanjia",
"Kesaba Panda Degree Womens College, Sorada",
"Kharasrota (Degree) Mahavidyalaya, Singhipur",
"Khetra Mohan Science (Degree) College, Narendrapur",
"Konark Bhagabati (Degree) College, Konark",
"Konark Women's (Degree) College, Sarada",
"Kotpad (Degree) College, Kotpad",
"Krishna Institute of Management & Science (KIMS), Bhubaneswar",
"Kshetra Mohan College of Basic Science, Balasore",
"Kshetrabasi Dayananda Anglovedic (Degree) College, Nirakarpur",
"Kuidana Indira Gandhi Memorial (Degree) College, Lilnepade",
"Kusum Devi Satsang Women's (Degree) College, Cuttack",
"Lachhaman Balajew (Degree) College, Angalo",
"Laxmi Barah (Degree) College, Ayatpur",
"Lochan Jagat Degree College, Karangamal",
"Lord Jagannath Degree Science College",
"Maa Manikeswari (Degree) College, Garh-Tumulia",
"Maa Maninaga Durga Mahila (Degree) Mahavidyalaya, Ranapur",
"Madhusudan Residential Degree College, Amalapada",
"Mahanadi (Degree) Mahavidyalaya, Kakhadi, Tangi",
"Mahanadi Vihar Women's (Degree) College, Cuttack",
"Mahanga Puspagiri (Degree) Mahavidyalaya, Erkana",
"Mahanga Womens (Degree) College, Pallisahi",
"Maharaja Purna Chandra (Autonomous) College, Takatpur",
"Mahatma Gandhi (Degree) College of Education & Technology, Astaranga",
"Mangala (Degree) Mahavidyalaya, Kakatpur",
"Mangalpur Women's (Degree) College, Mangalpur",
"Manmath Dhal Degree College, Biripata",
"Mayurbhanj College of Accountancy & Management (Degree), Takatpur",
"Meridian (Degree) College, Khandagiri",
"Model Degree College, Rayagada",
"Motto (Degree) College, Motto",
"Municipal (Degree) College, Uditnagar",
"Muniguda (Degree) College, Gobardhana",
"Naami (Degree) College, Naami",
"Narasingh Choudhury (Autonomous) College, Jajpur",
"Narasinghpur (Degree) College, Narasinghpur",
"National Institute of Science & Technology, (NIST) (Self-Financing)",
"Nayagarh (Autonomous) College, Nayagarh",
"Netaji Subash Chandra Bose (Degree) College, Sambalpur",
"Netaji Subash Memorial City (Degree) College, Cuttack",
"Newtonian Basic Sc. College, Nalamganj",
"Nice College of Commerce, Bolangir",
"NIIS Institute of Information Science & Management (Degree) College, Sarada Vihar",
"Niranjan Government (Degree) Women's College, Aska",
"Nuvapada Sri Balaji (Degree) Mahavidyalaya, Nuapada",
"Odapada Panchayat Samiti (Degree) Mahavidyalaya, Hindol Road",
"OMCC Degree College, Samaraipur",
"Pallishree (Degree) Mahila Mahavidyalaya, Banaram Chandrapur",
"Panabedha (Degree) Mahavidyalaya, Chandahandi",
"Panchayat Anchalik (Degree) Mahavidyalaya, Kumarbandh",
"Panchayat Samiti (Degree) College, Kolabira",
"Panchayat Samiti (Degree) College, Laikera",
"Panchyat (Degree) College, Phiringa",
"Pandit Nilakantha Utkal Academy Degree College, Chhatrapur",
"Parbati Giri Arts (Degree) College, Mahulpali",
"Pateswar (Degree) Mahavidyalaya, Suakati",
"Pattamundai (Degree) College, Pattamundai",
"Pattamundai Women's (Degree) College, Pattamundai",
"Pradosh Kumar Smruti Smaraki (Degree) College, H. Katapali",
"Pragati (Degree) College, Raisingpur, Bhawanipatna",
"Prananath (Autonomous) College, Khurda",
"Pratap Sasan (Degree) College, Balakati",
"Prince (Degree) College of Science, Ramnagar",
"Radha Krishna Degree College, Padwa",
"Raghunath Jew (Degree) Mahavidyalaya, Deulasahi",
"Rairangpur (Degree) College, Rairangpur",
"Raisuan (Degree) Mahavidyalaya, Raisuan",
"Raja Madhusudan Dev Degree College of Science & Education, Patia",
"Rajdhani (Degree) College, Bhubaneswar",
"RAJTARA DEGREE COLLEGE, SIDHAMADANGO",
"Rama Devi Women's University , Bhubaneswar (Erstwhile RD Autonomous College)",
"Rama Mani (Degree) Mahavidyalaya, Kantabada",
"Rani Suka Dei Mahila (Degree) Mahavidyalaya, Banki",
"Ratanpur Science (Degree) College, Ratanpur",
"Rayagada (Autonomous) College, Rayagada",
"Regional (Degree) College, Rambag",
"Rimuli (Degree) College, Rimuli",
"Rourkela College, Rourkela",
"Royal Degree College, Dharakote",
"Rural (Degree) Institute of Higher Studies, Bhogarai",
"Rushikulya (Degree) College, Surada",
"Rusimal (Degree) Mahavidyalaya, Bamunigam",
"Sadhu Goureswar (Degree) College, Kanikapada",
"Saheed Bhagat Singh (Degree) College, Khandadeuli",
"Saheed Raghu Dibakar (Degree) College, Garhbaniklo",
"Sai Adarsha Degree College",
"Sai Krupa +3 Science Residential College, Kunjakanta",
"Sai Smruti College, Daringbadi",
"Sakti Sai Degree College, Kuspangi",
"Salepur (Autonomous) College, Salepur",
"Samanta Chandra Sekhar (Autonomous) College, Puri",
"Samrat Degree College, Berhampur",
"Sanda (Degree) College, Sanda",
"Santh Asharamji Bapu Degree College, Kotagarh",
"Saraswati +3 Science (Degree) College, Bhawanipatna",
"Saraswati Degree College, Sialkhandahatha",
"Saraswati Degree Vidya Mandir, Neelakantha Nagar, Berhampur",
"Saswat (Degree) Mahavidyalaya, Jarasingha",
"Satyabhama Bal Residential Spiritual Degree College, Garhmadhupur",
"Semiliguda (Degree) College, Seimiliguda",
"Sevananda Saraswati (Degree) Mahavidyalaya, Bamakai",
"Shailabala Women's (Autonomous) College, Cuttack",
"Shastri Smruti (Degree) Mahavidyalaya, Baliput",
"Shrama Sakti (Degree) College, Biramitrapur",
"SMARTGURUKUL DEGREE COLLEGE, NABARANGPUR",
"Sovan Memorial Panchayat (Degree) College, Kirmira",
"Sri Aurobindo Institute of Higher Education, Research and Studies, Berhampur",
"Sri Baneswar (Degree) College, Bentapur",
"Sri Beleswar (Degree) Mahavidyalaya, Gondala",
"Sri Jaganath Mahavidyalaya, Rambha",
"SRI SAI RAMA KRISHNA DEGREE COLLEGE,, UPPALSINGH",
"Sri Sai Siddhi +3 Degree Sc. Residential College, Golapbag",
"Sri Sri Balunkeswar (Degree) Mahavidyalaya, Baruan",
"Sri Sri Jagannath (Degree) Mahavidyalaya, Rajnagar",
"Sriram +3 Science Residential College, Itwa",
"ST Xaviers College of Science and Technology",
"Sudha Kiran Degree College",
"Sulagna +3 Science Degree College, Sarita Nagar",
"Sushilabati Government Women's (Degree) College, Rourkela",
"Swami Vivekananda Memorial (Autonomous) College, Jagatsinghpur",
"Tarini Thakurani (Degree) Mahavidyalaya, Ghatagaon",
"Technoworld (Degree) College, Rairangpur",
"Times College of +3 Science & Commerce, Malipada",
"Udayanath (Autonomous) College of Science & Technology, Adaspur",
"Uniitech Degree College, College Road",
"Upendra Nath (Degree) College, Soro",
"Utkalmani Gopabandhu (Degree) Mahavidyalya, Mathili",
"Vedbyash Res. Degree College, Saradhabali, Berhampur",
"Vedvyas (Degree) Mahavidyalaya, Vedvyas",
"Vesaja Patel (Degree) College, Duduka",
"Vidya Degree College, Patharapada",
"Vigyan Internation Degree College, Pujariput",
"Vijayanjali +3 Science Degree College, Meghadambaru",
"Vikram Dev University, Jeypore",
"Vinayak Degree College, Samaraipur",
"Vishwa Vinayak Degree College, Khireitangiri",
"Vyasa Nagar (Autonomous) College, Jajpur Road",
"Women's (Degree) College, Kamakshyanagar",
"Women's (Degree) College, Paralakhemundi",
"Other"

];

function Pattamundai(Degree: any) {
  throw new Error("Function not implemented.");
}

